name: CI
on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint src
        run: |
          pip install ruff
          ruff check src
      - name: Import check
        run: python - << 'PY'
import importlib
import sys
for m in ["cv2","torch","yaml","pandas","numpy"]:
    importlib.import_module(m)
print("imports_ok")
PY
